export const INSTRUMENT_PROVDER_SET_IS_LOADING = "INSTRUMENT_PROVDER_SET_IS_LOADING";
export const INSTRUMENT_PROVIDER_SET_PIANO = "INSTRUMENT_PROVIDER_SET_PIANO";
export const INSTRUMENT_PROVIDER_SET_SELECTED_INSTRUMENT = "INSTRUMENT_PROVIDER_SET_SELECTED_INSTRUMENT";

export const PRACTICE_LOOP_CORRECT_GUESS = "PRACTICE_LOOP_CORRECT_GUESS";
export const PRACTICE_LOOP_WRONG_GUESS = "PRACTICE_LOOP_WRONG_GUESS";
export const PRACTICE_LOOP_INIT = "PRACTICE_LOOP_INIT";
export const PRACTICE_LOOP_NEW_QUESTION = "PRACTICE_LOOP_NEW_QUESTION";
export const PRACTICE_LOOP_SET_IS_QUESTION_PLAYING = "PRACTICE_LOOP_SET_IS_QUESTION_PLAYING";
export const PRACTICE_LOOP_MAX_STREAK_REACHED = "PRACTICE_LOOP_MAX_STREAK_REACHED";
export const PRACTICE_LOOP_SET_ACTIVE_NOTES = "PRACTICE_LOOP_SET_ACTIVE_NOTES";
export const PRACTICE_LOOP_SET_OPTIONS = "PRACTICE_LOOP_SET_OPTIONS";
export const PRACTICE_LOOP_RESET = "PRACTICE_LOOP_RESET";
export const PRACTICE_LOOP_SKIP_QUESTION = "PRACTICE_LOOP_SKIP_QUESTION";
export const PRACTICE_LOOP_RESET_AND_START_AGAIN = "PRACTICE_LOOP_RESET_AND_START_AGAIN";

export const APP_SET_IS_INTERACTIVE = "APP_SET_IS_INTERACTIVE";
export const APP_SET_IS_LOADING = "APP_SET_IS_LOADING";
export const APP_SET_SHOULD_SHOW_VOLUME_WARNINIG = "APP_SET_SHOULD_SHOW_VOLUME_WARNINIG";

export const ROUTER_LOCATION_CHANGE = "@@router/LOCATION_CHANGE";

export const SINGLE_NOTE_SCREEN_SET_NOTE_TO_GUESS = "SINGLE_NOTE_SCREEN_SET_NOTE_TO_GUESS";

export const INTERVAL_IDENTIFICATION_SCREEN_SET_NEW_QUESTION = "INTERVAL_IDENTIFICATION_SCREEN_SET_NEW_QUESTION";
export const INTERVAL_IDENTIFICATION_SCREEN_SET_OPTIONS = "INTERVAL_IDENTIFICATION_SCREEN_SET_OPTIONS";

export const CHORD_QUALITY_SCREEN_SET_CHORD_TO_GUESS = "CHORD_QUALITY_SCREEN_SET_CHORD_TO_GUESS";
export const CHORD_QUALITY_SCREEN_SET_OPTIONS = "CHORD_QUALITY_SCREEN_SET_OPTIONS";

export const RHYTHM_TRANSCRIPTION_SCREEN_SET_CORRECT_CHOICE = "RHYTHM_TRANSCRIPTION_SCREEN_SET_CORRECT_CHOICE";
export const RHYTHM_TRANSCRIPTION_SCREEN_SET_CHOICES = "RHYTHM_TRANSCRIPTION_SCREEN_SET_CHOICES";

export const LESSON_DATA_SET_IS_LOADING = "LESSON_DATA_SET_IS_LOADING";

export const ACCOUNT_SET_IS_LOADING = "ACCOUNT_SET_IS_LOADING";
export const ACCOUNT_SET_IS_SETUP_COMPLETE = "ACCOUNT_SET_IS_SETUP_COMPLETE";
export const ACCOUNT_SET_IS_SUBSCRIBED = "ACCOUNT_SET_IS_SUBSCRIBED";
export const ACCOUNT_SET_IS_LOADING_SUBSCRIBED_STATUS = "ACCOUNT_SET_IS_LOADING_SUBSCRIBED_STATUS";
export const ACCOUNT_SET_IS_ONBOARDED = "ACCOUNT_SET_IS_ONBOARDED";
export const ACCOUNT_SET_IS_LOADING_ONBOARDED_STATUS = "ACCOUNT_SET_IS_LOADING_ONBOARDED_STATUS";

export const SOUND_EFFECTS_SET_IS_LOADING = "SOUND_EFFECTS_SET_IS_LOADING";
export const SOUND_EFFECTS_SET_CORRECT_SOUND_EFFECT = "SOUND_EFFECTS_SET_CORRECT_SOUND_EFFECT";
export const SOUND_EFFECTS_SET_WRONG_SOUND_EFFECT = "SOUND_EFFECTS_SET_WRONG_SOUND_EFFECT";

export const ENHARMONIC_NOTES_EXERCISE_SCREEN_SET_NOTES = "ENHARMONIC_NOTES_EXERCISE_SCREEN_SET_NOTES";
export const NOTE_DISTANCE_EXERCISE_SCREEN_SET_QUESTION = "NOTE_DISTANCE_EXERCISE_SCREEN_SET_QUESTION";
export const NOTE_DISTANCE_EXERCISE_SCREEN_SET_AVAILABLE_CHOICES = "NOTE_DISTANCE_EXERCISE_SCREEN_SET_AVAILABLE_CHOICES";

export const CUSTOM_EXERCISES_SET_OPTIONS_AND_TITLE = "CUSTOM_EXERCISES_SET_OPTIONS_AND_TITLE";
export const CUSTOM_EXERCISES_SET_CATEGORY_ID = "CUSTOM_EXERCISES_SET_CATEGORY_ID";
export const CUSTOM_EXERCISES_SET_SUB_CATEGORY_ID = "CUSTOM_EXERCISES_SET_SUB_CATEGORY_ID";
export const CUSTOM_EXERCISES_SET_IS_EDITING = "CUSTOM_EXERCISES_SET_IS_EDITING";