[build]
  command = "gatsby build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[dev]
  command = "./dev.sh"
  targetPort = 8000
  framework = "#custom"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/app/*"
  to = "/app/"
  status = 200
