import {
  MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_2NDS_ID, MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_3RD_ID, MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_PERFECT_4THS_AND_5THS_ID, MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_6THS_ID, MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_7THS_ID 
} from "../../store/firebase/accountSetup";

export default {
  [MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_2NDS_ID]: ["1A", "2M"],
  [MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_3RD_ID]: ["3m", "3M"],
  [MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_PERFECT_4THS_AND_5THS_ID]: ["4P", "5P"],
  [MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_6THS_ID]: ["6m", "6M"],
  [MUSIC_THEORY_EXERCISES_NOTE_DISTANCES_MINOR_MAJOR_7THS_ID]: ["7m", "7M"]
};