// Descriptions for scale types, keyed by scale name (matches scale.name from data)
// Used to add educational content to scale pages.

export const scaleDescriptions = {
  "major": "The major scale is the most fundamental scale in Western music theory. Its pattern of whole and half steps (W-W-H-W-W-W-H) produces a bright, happy, and resolved sound. Nearly all of Western harmony, melody, and music theory is built upon the major scale and its relationships.",
  "minor": "The natural minor scale, also known as the Aeolian mode, is the second most important scale in Western music. Its lowered 3rd, 6th, and 7th degrees compared to the major scale give it a dark, sad, and introspective quality. It is the foundation of minor key harmony used across all genres.",
  "ionian": "The Ionian mode is identical to the major scale and is the first of the seven diatonic modes. It produces a bright, happy, and stable sound due to its major third and major seventh. Understanding it as a mode helps when studying modal harmony and improvisation in jazz and fusion.",
  "dorian": "The Dorian mode is a minor scale with a raised 6th degree, giving it a brighter and jazzier sound than the natural minor. It is one of the most widely used modes in jazz improvisation, funk, and blues. The characteristic raised 6th makes it perfect for playing over minor 7th chords.",
  "phrygian": "The Phrygian mode is a minor scale with a lowered 2nd degree, giving it a dark, Spanish, and exotic sound. The half step between the first and second notes creates its distinctive character. It is commonly used in flamenco, metal, Middle Eastern-influenced music, and dramatic film scores.",
  "lydian": "The Lydian mode is a major scale with a raised 4th degree, producing a bright, dreamy, and floating sound. The augmented fourth gives it an ethereal quality that sets it apart from the standard major scale. It is a favorite in jazz, film scoring, and progressive rock for its uplifting character.",
  "mixolydian": "The Mixolydian mode is a major scale with a lowered 7th degree, creating a sound that is bright but with a bluesy edge. It is the natural choice for playing over dominant 7th chords. Mixolydian is essential in blues, rock, country, funk, and jazz improvisation.",
  "aeolian": "The Aeolian mode, identical to the natural minor scale, is built on the 6th degree of the major scale. It has a melancholic and introspective sound due to its minor third, minor sixth, and minor seventh. It is the basis of minor key harmony in virtually all Western music genres.",
  "locrian": "The Locrian mode is the darkest and most unstable of the seven diatonic modes. Its diminished fifth makes even the tonic chord feel unresolved. While rarely used as a tonal center, Locrian is important for improvising over half-diminished chords in jazz and for creating extreme tension in metal.",
  "harmonic minor": "The harmonic minor scale raises the 7th degree of the natural minor scale, creating a leading tone that pulls strongly toward the tonic. This produces the characteristic augmented second interval between the 6th and 7th degrees, giving it a dramatic, Middle Eastern, or classical sound. It is essential for minor key harmony.",
  "melodic minor": "The melodic minor scale raises both the 6th and 7th degrees of the natural minor when ascending, smoothing out the awkward augmented second of the harmonic minor. In jazz, the ascending form is used both up and down. It is the parent scale for many important jazz modes and chord-scale relationships.",
  "blues": "The blues scale adds a flat 5th (the 'blue note') to the minor pentatonic scale, creating its signature gritty, soulful sound. This six-note scale is the foundation of blues music and is widely used in rock, jazz, funk, and R&B. The blue note creates the expressive tension that defines the blues feel.",
  "major pentatonic": "The major pentatonic scale is a five-note scale derived from the major scale by removing the 4th and 7th degrees. This eliminates all half steps, producing a consonant, pleasant, and universally appealing sound. It is used across virtually every musical tradition worldwide, from folk to pop to country to rock.",
  "minor pentatonic": "The minor pentatonic scale is a five-note scale built from the minor scale by removing the 2nd and 6th degrees. Its simplicity and strong sound make it the most commonly used scale for soloing in rock, blues, and pop. It is often the first scale guitarists learn for improvisation.",
  "major blues": "The major blues scale adds a flat 3rd (the blue note) to the major pentatonic scale, blending major brightness with bluesy grit. It creates a warm, soulful sound that works well over major and dominant chords. It is commonly used in blues, gospel, country, and jazz improvisation.",
  "minor blues": "The minor blues scale is another name for the standard blues scale, combining the minor pentatonic with an added flat 5th. It is the quintessential scale for blues soloing, producing the raw, emotional sound that defines the genre. It works over both minor and dominant 7th chords.",
  "chromatic": "The chromatic scale contains all twelve notes in Western music, each a half step apart. It is not typically used as a key center but rather as a passing-tone device for creating tension, color, and smooth voice leading. Chromatic runs appear in virtually every genre from classical to jazz to metal.",
  "whole tone": "The whole tone scale is a six-note symmetrical scale built entirely of whole steps. It has a dreamy, floating, and ambiguous sound with no clear tonal center. It was famously used by Debussy and is common in jazz, film scoring, and any context where a sense of suspended reality is desired.",
  "diminished": "The diminished scale, also called the octatonic scale, alternates between whole and half steps, creating an eight-note symmetrical scale. Its repeating pattern gives it a dark, mysterious, and tense quality. It is widely used in jazz improvisation over diminished chords and in classical and film music.",
  "half-whole diminished": "The half-whole diminished scale starts with a half step and alternates half and whole steps. It is the primary choice for improvising over dominant 7th chords with altered tensions (b9, #9, #11). It is an essential tool in jazz, creating a tense, colorful sound over dominant harmony.",
  "whole-half diminished": "The whole-half diminished scale starts with a whole step and alternates whole and half steps. It is typically used over diminished 7th chords, producing a dark and symmetrical sound. Each note can function as a potential root, making it useful for modulation in jazz and classical music.",
  "bebop": "The bebop scale adds a chromatic passing tone to a seven-note scale, creating an eight-note scale that aligns chord tones with strong beats when played in eighth notes. This was a revolutionary concept in jazz, allowing improvisers to play flowing lines while emphasizing harmony. It is fundamental to jazz improvisation.",
  "bebop major": "The bebop major scale adds a chromatic passing tone (b6) between the 5th and 6th degrees of the major scale. This eight-note scale keeps chord tones on the beat during eighth-note lines, a crucial concept in jazz. It is used over major 7th chords in bebop and mainstream jazz.",
  "bebop minor": "The bebop minor scale adds a chromatic passing tone between the 5th and 6th degrees of the Dorian mode. This keeps the guide tones of the minor 7th chord aligned with strong beats during improvisation. It is a key tool for jazz musicians soloing over minor 7th chords.",
  "spanish": "The Spanish scale, closely related to the Phrygian dominant mode, has a distinctly flamenco and Andalusian sound. Its characteristic flat 2nd and major 3rd create the exotic tension associated with Spanish music. It is widely used in flamenco guitar, Latin jazz, and any music evoking a Mediterranean atmosphere.",
  "hungarian minor": "The Hungarian minor scale, also called the Gypsy minor, features augmented second intervals that give it a dramatic and exotic Eastern European sound. It combines elements of the harmonic minor with a raised 4th degree. It is associated with Romani music, Hungarian folk, and dramatic classical compositions.",
  "phrygian dominant": "The Phrygian dominant scale is the 5th mode of the harmonic minor scale. It has a flat 2nd like the Phrygian mode but with a major 3rd, creating a sound strongly associated with Middle Eastern, Jewish, and flamenco music. It is commonly used over dominant chords resolving to minor.",
  "double harmonic major": "The double harmonic major scale, also known as the Byzantine or Arabic scale, features two augmented seconds that give it a highly exotic and dramatic sound. It is commonly used in Middle Eastern, Indian, and Eastern European music. Its symmetrical structure makes it uniquely colorful among heptatonic scales.",
  "persian": "The Persian scale has a dark, exotic sound with characteristic augmented second intervals. It evokes the musical traditions of Iran and the broader Middle East. It is used to create atmospheric, mystical, and dramatic musical passages in both traditional Persian music and Western compositions seeking an Eastern flavor.",
  "arabian": "The Arabian scale captures the essence of traditional Middle Eastern music with its characteristic intervals. It features augmented seconds that create the exotic, ornamental sound associated with Arabic musical traditions. It is used in traditional Arabic music, belly dance music, and Western compositions seeking an Eastern atmosphere.",
  "flamenco": "The flamenco scale is closely related to the Phrygian mode and Phrygian dominant, capturing the passionate and dramatic essence of Spanish flamenco music. Its characteristic flat second creates tension and emotional intensity. It is essential for flamenco guitar and is also used in Latin jazz and fusion.",
  "indian": "The Indian scale reflects the melodic patterns found in traditional Indian classical music (raga system). It captures the meditative and expressive qualities of Indian musical traditions. This scale is used to evoke the atmosphere of Indian music in both traditional and contemporary Western fusion contexts.",
  "enigmatic": "The enigmatic scale is a rare and unusual scale with an unpredictable interval pattern. It was devised by Giuseppe Verdi and features a unique combination of intervals that defy conventional tonal expectations. It is used primarily in avant-garde and contemporary classical music for its mysterious and ambiguous quality.",
};

// Fallback description for scale types not in the list above
export const scaleDefaultDescription = "This scale has a unique pattern of intervals that gives it a distinctive sound and character. Exploring unfamiliar scales is a great way to break out of musical patterns and discover new melodic possibilities. Try playing it over different chords to hear how its unique intervals create various moods and colors.";
